[package]
name = "rust-solv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }